-- 코드를 작성해주세요
WITH EMP_TOT_SCORE AS (
    SELECT 
        EMP_NO,
        SUM(SCORE) AS SCORE
    FROM HR_GRADE
    GROUP BY EMP_NO
)

SELECT T.SCORE, E.EMP_NO, E.EMP_NAME, E.POSITION, E.EMAIL
FROM HR_EMPLOYEES E
JOIN EMP_TOT_SCORE T ON E.EMP_NO = T.EMP_NO
ORDER BY SCORE DESC LIMIT 1