-- 코드를 작성해주세요
SELECT
    YEAR(DIFFERENTIATION_DATE) AS YEAR,
    M.MAX_SIZE - SIZE_OF_COLONY AS YEAR_DEV,
    ID
FROM ECOLI_DATA
JOIN (
    SELECT 
        YEAR(DIFFERENTIATION_DATE) AS YEAR,
        MAX(SIZE_OF_COLONY) AS MAX_SIZE
    FROM ECOLI_DATA
    GROUP BY YEAR(DIFFERENTIATION_DATE)
) M ON M.YEAR = YEAR(DIFFERENTIATION_DATE)
ORDER BY 
    YEAR(DIFFERENTIATION_DATE),
    M.MAX_SIZE - SIZE_OF_COLONY